---
abstract: 'run a system command or spawn a system processes'
author:
  - 'Mark Lawrence <nomad@null.net>, based heavily on'
build_requires:
  Cwd: 0
  Data::Dumper: 0
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Cmd
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Cwd: 0
  File::Which: 0
  File::chdir: 0.08
  IO::Handle: 0
  IPC::Open3: 0
  Log::Any: 0
  Moo: 0
  Sub::Exporter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mlawren/sys-cmd
version: 0.07_2
